// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8uGt9jWIxqEYjQosXdxGRVQEtPPwX37g',
    appId: '1:580184804861:web:5bdda76a804d0eced55d94',
    messagingSenderId: '580184804861',
    projectId: 'food-recipe-app-33140',
    authDomain: 'food-recipe-app-33140.firebaseapp.com',
    storageBucket: 'food-recipe-app-33140.firebasestorage.app',
    measurementId: 'G-LTW16TZYN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzx5w3IM5HAYXNHHXV3tyBeWBy4tEZ50',
    appId: '1:580184804861:android:3493c06b0beb8c0ed55d94',
    messagingSenderId: '580184804861',
    projectId: 'food-recipe-app-33140',
    storageBucket: 'food-recipe-app-33140.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJKRAWgFgJS6N-ow8GWr5yicTOQKoivUQ',
    appId: '1:580184804861:ios:762047b1d0465558d55d94',
    messagingSenderId: '580184804861',
    projectId: 'food-recipe-app-33140',
    storageBucket: 'food-recipe-app-33140.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJKRAWgFgJS6N-ow8GWr5yicTOQKoivUQ',
    appId: '1:580184804861:ios:762047b1d0465558d55d94',
    messagingSenderId: '580184804861',
    projectId: 'food-recipe-app-33140',
    storageBucket: 'food-recipe-app-33140.firebasestorage.app',
    iosBundleId: 'com.example.foodRecipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8uGt9jWIxqEYjQosXdxGRVQEtPPwX37g',
    appId: '1:580184804861:web:f031a61d4340101ad55d94',
    messagingSenderId: '580184804861',
    projectId: 'food-recipe-app-33140',
    authDomain: 'food-recipe-app-33140.firebaseapp.com',
    storageBucket: 'food-recipe-app-33140.firebasestorage.app',
    measurementId: 'G-JTQ88RN41E',
  );
}
